version: '3'
tasks:
  init:
    cmds:
      - pnpm install
      - pnpm --filter shared build
      - docker compose up -d
  dev:
    cmds:
      - pnpm -w dlx concurrently "pnpm --filter ai-service dev" "pnpm --filter n8n-ui dev"
  build:
    cmds:
      - pnpm -r build
  lint:
    cmds:
      - pnpm -r lint
